#pragma once

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif
#include "wx/event.h"
#include "wx/sizer.h"
#include "wx/gbsizer.h"
#include "wx/minifram.h"
#include "wx/statline.h"
#include "wx/notebook.h"
#include "wx/spinctrl.h"
#include "wx/wrapsizer.h"
#include "wx/generic/stattextg.h"
#include "wx/html/htmlwin.h"
#include "wx/persist/toplevel.h"
#include "wx/aboutdlg.h"
#include "wx/numdlg.h"
#include "wx/progdlg.h"
#include "wx/socket.h"
#include "wx/url.h"
#include "wx/sstream.h"
#include "wx/thread.h"
#include "wx/dcbuffer.h"
#include "wx/dcgraph.h"
#include "wx/overlay.h"
#include "wx/graphics.h"
#include "wx/minifram.h"
#include "wx/config.h"
#include "MainFrame.h"
#include "TrackFrame.h"

#include "STC1200TCP.h"

///////////////////////////////////////////////////////////////////////////////
// DRC1200App Main Application Class

class MainFrame;

wxDECLARE_APP(DRC1200App);

class DRC1200App : public wxApp
{
public:
	DRC1200App();
	~DRC1200App();

    wxConfig* GetConfig(void)
    { return m_pConfig; }

	MainFrame* GetMainFrame(void)
	{ return m_pMainFrame; }

	TimePanel* m_panelTime;
	OptionPanel* m_panelOption;
	VelocityPanel* m_panelVelocity;

public:
	virtual bool OnInit() override;
    virtual int OnExit() override;

//private:
	MainFrame* m_pMainFrame;
	wxConfig* m_pConfig;
	size_t  m_trackCount;       /* num of tracks machine supports 8, 16 or 24 */
    bool    m_dcsFound;         /* true if DCS track controller found */
	wxString m_strHostArg;
	// Generic colors
	wxColor m_colorBlack;
	wxColor m_colorWhite;
	// Frame, panel and basic text colors
	wxColor m_colorFrame;
	wxColor m_colorPanel;
	wxColor m_colorText;
	wxColor m_colorTime;
	wxColor m_colorTimeBkgnd;
	wxColor m_colorError;
	// Button text colors
	wxColor m_colorBtnText;
	wxColor m_colorBtnTextDim;
	wxColor m_colorBtnTextActive;
	// Button face colors
	wxColor m_colorBtnFace;
	wxColor m_colorBtnGrey;
	wxColor m_colorBtnDark;
	wxColor m_colorBtnActive;
	wxColor m_colorBtnRecReady;
	wxColor m_colorBtnRecActive;
	wxColor m_colorBtnModeInput;
	wxColor m_colorBtnModeRepro;
	wxColor m_colorBtnModeSync;
	wxColor m_colorBtnModeMon;
};

#define GET_MAX_TRACKS()		( wxGetApp().m_trackCount )
#define IS_DCS_FOUND()			( wxGetApp().m_dcsFound )

///////////////////////////////////////////////////////////////////////////////
// Controls and Menu ID Constants

enum
{
	ID_CONNECT_EXIT = wxID_EXIT,

	ID_USER_START = wxID_HIGHEST + 1001,

	ID_CONNECT_CLOSE,
	ID_CONNECT_TCP,

	ID_TRACK_RECORD_READY,
	ID_RECORD_TRACK1,
	ID_RECORD_TRACK2,
	ID_RECORD_TRACK3,
	ID_RECORD_TRACK4,
	ID_RECORD_TRACK5,
	ID_RECORD_TRACK6,
	ID_RECORD_TRACK7,
	ID_RECORD_TRACK8,
	ID_RECORD_TRACK9,
	ID_RECORD_TRACK10,
	ID_RECORD_TRACK11,
	ID_RECORD_TRACK12,
	ID_RECORD_TRACK13,
	ID_RECORD_TRACK14,
	ID_RECORD_TRACK15,
	ID_RECORD_TRACK16,
	ID_RECORD_TRACK17,
	ID_RECORD_TRACK18,
	ID_RECORD_TRACK19,
	ID_RECORD_TRACK20,
	ID_RECORD_TRACK21,
	ID_RECORD_TRACK22,
	ID_RECORD_TRACK23,
	ID_RECORD_TRACK24,

	ID_TRACK_SOURCE_MODE,
	ID_SOURCE_INPUT,
	ID_SOURCE_REPRO,
	ID_SOURCE_SYNC,

    ID_TRACK_MONITOR_MODE,
	ID_INPUT_TRACK1,
	ID_INPUT_TRACK2,
	ID_INPUT_TRACK3,
	ID_INPUT_TRACK4,
	ID_INPUT_TRACK5,
	ID_INPUT_TRACK6,
	ID_INPUT_TRACK7,
	ID_INPUT_TRACK8,
	ID_INPUT_TRACK9,
	ID_INPUT_TRACK10,
	ID_INPUT_TRACK11,
	ID_INPUT_TRACK12,
	ID_INPUT_TRACK13,
	ID_INPUT_TRACK14,
	ID_INPUT_TRACK15,
	ID_INPUT_TRACK16,
	ID_INPUT_TRACK17,
	ID_INPUT_TRACK18,
	ID_INPUT_TRACK19,
	ID_INPUT_TRACK20,
	ID_INPUT_TRACK21,
	ID_INPUT_TRACK22,
	ID_INPUT_TRACK23,
	ID_INPUT_TRACK24,

	ID_REPRO_TRACK1,
	ID_REPRO_TRACK2,
	ID_REPRO_TRACK3,
	ID_REPRO_TRACK4,
	ID_REPRO_TRACK5,
	ID_REPRO_TRACK6,
	ID_REPRO_TRACK7,
	ID_REPRO_TRACK8,
	ID_REPRO_TRACK9,
	ID_REPRO_TRACK10,
	ID_REPRO_TRACK11,
	ID_REPRO_TRACK12,
	ID_REPRO_TRACK13,
	ID_REPRO_TRACK14,
	ID_REPRO_TRACK15,
	ID_REPRO_TRACK16,
	ID_REPRO_TRACK17,
	ID_REPRO_TRACK18,
	ID_REPRO_TRACK19,
	ID_REPRO_TRACK20,
	ID_REPRO_TRACK21,
	ID_REPRO_TRACK22,
	ID_REPRO_TRACK23,
	ID_REPRO_TRACK24,

	ID_SYNC_TRACK1,
	ID_SYNC_TRACK2,
	ID_SYNC_TRACK3,
	ID_SYNC_TRACK4,
	ID_SYNC_TRACK5,
	ID_SYNC_TRACK6,
	ID_SYNC_TRACK7,
	ID_SYNC_TRACK8,
	ID_SYNC_TRACK9,
	ID_SYNC_TRACK10,
	ID_SYNC_TRACK11,
	ID_SYNC_TRACK12,
	ID_SYNC_TRACK13,
	ID_SYNC_TRACK14,
	ID_SYNC_TRACK15,
	ID_SYNC_TRACK16,
	ID_SYNC_TRACK17,
	ID_SYNC_TRACK18,
	ID_SYNC_TRACK19,
	ID_SYNC_TRACK20,
	ID_SYNC_TRACK21,
	ID_SYNC_TRACK22,
	ID_SYNC_TRACK23,
	ID_SYNC_TRACK24,

	ID_MONITOR_TRACK1,
	ID_MONITOR_TRACK2,
	ID_MONITOR_TRACK3,
	ID_MONITOR_TRACK4,
	ID_MONITOR_TRACK5,
	ID_MONITOR_TRACK6,
	ID_MONITOR_TRACK7,
	ID_MONITOR_TRACK8,
	ID_MONITOR_TRACK9,
	ID_MONITOR_TRACK10,
	ID_MONITOR_TRACK11,
	ID_MONITOR_TRACK12,
	ID_MONITOR_TRACK13,
	ID_MONITOR_TRACK14,
	ID_MONITOR_TRACK15,
	ID_MONITOR_TRACK16,
	ID_MONITOR_TRACK17,
	ID_MONITOR_TRACK18,
	ID_MONITOR_TRACK19,
	ID_MONITOR_TRACK20,
	ID_MONITOR_TRACK21,
	ID_MONITOR_TRACK22,
	ID_MONITOR_TRACK23,
	ID_MONITOR_TRACK24,

	ID_BUTTON_MONITOR_TRACK1,
	ID_BUTTON_MONITOR_TRACK2,
	ID_BUTTON_MONITOR_TRACK3,
	ID_BUTTON_MONITOR_TRACK4,
	ID_BUTTON_MONITOR_TRACK5,
	ID_BUTTON_MONITOR_TRACK6,
	ID_BUTTON_MONITOR_TRACK7,
	ID_BUTTON_MONITOR_TRACK8,
	ID_BUTTON_MONITOR_TRACK9,
	ID_BUTTON_MONITOR_TRACK10,
	ID_BUTTON_MONITOR_TRACK11,
	ID_BUTTON_MONITOR_TRACK12,
	ID_BUTTON_MONITOR_TRACK13,
	ID_BUTTON_MONITOR_TRACK14,
	ID_BUTTON_MONITOR_TRACK15,
	ID_BUTTON_MONITOR_TRACK16,
	ID_BUTTON_MONITOR_TRACK17,
	ID_BUTTON_MONITOR_TRACK18,
	ID_BUTTON_MONITOR_TRACK19,
	ID_BUTTON_MONITOR_TRACK20,
	ID_BUTTON_MONITOR_TRACK21,
	ID_BUTTON_MONITOR_TRACK22,
	ID_BUTTON_MONITOR_TRACK23,
	ID_BUTTON_MONITOR_TRACK24,

	ID_TRACK_ALLSAFE,
	ID_TRACK_ALLREADY,
	ID_TRACK_ALLINPUT,
	ID_TRACK_ALLREPRO,
	ID_TRACK_ALLSYNC,
    ID_TRACK_SAVETODISK,
    ID_TRACK_LOADFROMDISK,
	ID_TRACK_CONFIGURATION,
	ID_TRACK_ALLMONITORON,
	ID_TRACK_ALLMONITOROFF,
	ID_TRACK_STANDBYMONITOR,

    ID_CONFIGURATION_SAVE,
    ID_CONFIGURATION_RECALL,
    ID_CONFIGURATION_RESET,

    ID_TOGGLEMODE_TRACK1,
    ID_TOGGLEMODE_TRACK2,
    ID_TOGGLEMODE_TRACK3,
    ID_TOGGLEMODE_TRACK4,
    ID_TOGGLEMODE_TRACK5,
    ID_TOGGLEMODE_TRACK6,
    ID_TOGGLEMODE_TRACK7,
    ID_TOGGLEMODE_TRACK8,
    ID_TOGGLEMODE_TRACK9,
    ID_TOGGLEMODE_TRACK10,
    ID_TOGGLEMODE_TRACK11,
    ID_TOGGLEMODE_TRACK12,
    ID_TOGGLEMODE_TRACK13,
    ID_TOGGLEMODE_TRACK14,
    ID_TOGGLEMODE_TRACK15,
    ID_TOGGLEMODE_TRACK16,
    ID_TOGGLEMODE_TRACK17,
    ID_TOGGLEMODE_TRACK18,
    ID_TOGGLEMODE_TRACK19,
    ID_TOGGLEMODE_TRACK20,
    ID_TOGGLEMODE_TRACK21,
    ID_TOGGLEMODE_TRACK22,
    ID_TOGGLEMODE_TRACK23,
    ID_TOGGLEMODE_TRACK24,

	ID_TRANSPORT_RECORD,
	ID_TRANSPORT_PLAY,
	ID_TRANSPORT_REWIND,
	ID_TRANSPORT_FORWARD,
	ID_TRANSPORT_STOP,
	ID_TRANSPORT_PUNCH,
    ID_TRANSPORT_TOGGLEPLAY,
	ID_TRANSPORT_TAPELIFTER,
    ID_TAPESPEED_HIGHSPEED,
    ID_TAPESPEED_LOWSPEED,
	ID_TRANSPORT_LIBRARYWIND,

	ID_SEARCH_MARKIN,
	ID_SEARCH_MARKOUT,
	ID_SEARCH_PUNCHIN,
	ID_SEARCH_PUNCHOUT,
	ID_SEARCH_ZERORETURN,

	ID_LOCATOR_CUEMODE,
	ID_LOCATOR_STOREMODE,
	ID_LOCATOR_SEARCH,
	ID_LOCATOR_CANCELSEARCH,
	ID_LOCATOR_AUTOLOOP,
	ID_LOCATOR_MARKIN,
	ID_LOCATOR_MARKOUT,
	ID_LOCATOR_AUTOPUNCH,
	ID_LOCATOR_PUNCHIN,
	ID_LOCATOR_PUNCHOUT,
	ID_LOCATOR_RESETCOUNTER,
	ID_LOCATOR_AUTOPLAY,

    ID_CUEPOINT_LOC0,
    ID_CUEPOINT_LOC1,
    ID_CUEPOINT_LOC2,
    ID_CUEPOINT_LOC3,
    ID_CUEPOINT_LOC4,
    ID_CUEPOINT_LOC5,
    ID_CUEPOINT_LOC6,
    ID_CUEPOINT_LOC7,
    ID_CUEPOINT_LOC8,
    ID_CUEPOINT_LOC9,
    ID_CUEPOINT_MARKIN,
    ID_CUEPOINT_MARKOUT,
    ID_CUEPOINT_PUNCHIN,
    ID_CUEPOINT_PUNCHOUT,

	ID_MEMORY,
	ID_EDITTIME_LOC0,
	ID_EDITTIME_LOC1,
	ID_EDITTIME_LOC2,
	ID_EDITTIME_LOC3,
	ID_EDITTIME_LOC4,
	ID_EDITTIME_LOC5,
	ID_EDITTIME_LOC6,
	ID_EDITTIME_LOC7,
	ID_EDITTIME_LOC8,
	ID_EDITTIME_LOC9,
	ID_EDITTIME_MARKIN,
	ID_EDITTIME_MARKOUT,
	ID_EDITTIME_PUNCHIN,
	ID_EDITTIME_PUNCHOUT,
	ID_EDITTIME_RTZ,
	ID_MEMORY_CLEARALL,
	ID_MEMORY_SAVETODISK,
	ID_MEMORY_LOADFROMDISK,

    ID_SMPTE,
    ID_GENERATOR_STOP,
    ID_GENERATOR_START,
    ID_GENERATOR_RESUME,
    ID_GENERATOR_EDITTIME,

	ID_VIEW_SHOWTRACKS,
	ID_VIEW_HIDETRACKS,

    ID_CHECK_AUTOPLAY,
	ID_CHECK_LIBRARYWIND,
	ID_CHECK_STANDBYMON,

	ID_HELP,
	ID_ABOUT,

	SOCKET_ID,
	CONNECT_ID
};
