#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = `wx-config --cflags` -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = `wx-config --libs`

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/DRC1200

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/DRC1200

OBJ_DEBUG = $(OBJDIR_DEBUG)/VelocityPanel.o $(OBJDIR_DEBUG)/TrackFrame.o $(OBJDIR_DEBUG)/TimePanel.o $(OBJDIR_DEBUG)/STCCommand.o $(OBJDIR_DEBUG)/ConnectDialog.o $(OBJDIR_DEBUG)/MainFramePanel.o $(OBJDIR_DEBUG)/MainFrameMenu.o $(OBJDIR_DEBUG)/MainFrameHelper.o $(OBJDIR_DEBUG)/MainFrame.o $(OBJDIR_DEBUG)/DRC1200App.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/VelocityPanel.o $(OBJDIR_RELEASE)/TrackFrame.o $(OBJDIR_RELEASE)/TimePanel.o $(OBJDIR_RELEASE)/STCCommand.o $(OBJDIR_RELEASE)/ConnectDialog.o $(OBJDIR_RELEASE)/MainFramePanel.o $(OBJDIR_RELEASE)/MainFrameMenu.o $(OBJDIR_RELEASE)/MainFrameHelper.o $(OBJDIR_RELEASE)/MainFrame.o $(OBJDIR_RELEASE)/DRC1200App.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/VelocityPanel.o: VelocityPanel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c VelocityPanel.cpp -o $(OBJDIR_DEBUG)/VelocityPanel.o

$(OBJDIR_DEBUG)/TrackFrame.o: TrackFrame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c TrackFrame.cpp -o $(OBJDIR_DEBUG)/TrackFrame.o

$(OBJDIR_DEBUG)/TimePanel.o: TimePanel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c TimePanel.cpp -o $(OBJDIR_DEBUG)/TimePanel.o

$(OBJDIR_DEBUG)/STCCommand.o: STCCommand.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c STCCommand.cpp -o $(OBJDIR_DEBUG)/STCCommand.o

$(OBJDIR_DEBUG)/ConnectDialog.o: ConnectDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ConnectDialog.cpp -o $(OBJDIR_DEBUG)/ConnectDialog.o

$(OBJDIR_DEBUG)/MainFramePanel.o: MainFramePanel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MainFramePanel.cpp -o $(OBJDIR_DEBUG)/MainFramePanel.o

$(OBJDIR_DEBUG)/MainFrameMenu.o: MainFrameMenu.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MainFrameMenu.cpp -o $(OBJDIR_DEBUG)/MainFrameMenu.o

$(OBJDIR_DEBUG)/MainFrameHelper.o: MainFrameHelper.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MainFrameHelper.cpp -o $(OBJDIR_DEBUG)/MainFrameHelper.o

$(OBJDIR_DEBUG)/MainFrame.o: MainFrame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MainFrame.cpp -o $(OBJDIR_DEBUG)/MainFrame.o

$(OBJDIR_DEBUG)/DRC1200App.o: DRC1200App.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DRC1200App.cpp -o $(OBJDIR_DEBUG)/DRC1200App.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/VelocityPanel.o: VelocityPanel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c VelocityPanel.cpp -o $(OBJDIR_RELEASE)/VelocityPanel.o

$(OBJDIR_RELEASE)/TrackFrame.o: TrackFrame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c TrackFrame.cpp -o $(OBJDIR_RELEASE)/TrackFrame.o

$(OBJDIR_RELEASE)/TimePanel.o: TimePanel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c TimePanel.cpp -o $(OBJDIR_RELEASE)/TimePanel.o

$(OBJDIR_RELEASE)/STCCommand.o: STCCommand.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c STCCommand.cpp -o $(OBJDIR_RELEASE)/STCCommand.o

$(OBJDIR_RELEASE)/ConnectDialog.o: ConnectDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ConnectDialog.cpp -o $(OBJDIR_RELEASE)/ConnectDialog.o

$(OBJDIR_RELEASE)/MainFramePanel.o: MainFramePanel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MainFramePanel.cpp -o $(OBJDIR_RELEASE)/MainFramePanel.o

$(OBJDIR_RELEASE)/MainFrameMenu.o: MainFrameMenu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MainFrameMenu.cpp -o $(OBJDIR_RELEASE)/MainFrameMenu.o

$(OBJDIR_RELEASE)/MainFrameHelper.o: MainFrameHelper.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MainFrameHelper.cpp -o $(OBJDIR_RELEASE)/MainFrameHelper.o

$(OBJDIR_RELEASE)/MainFrame.o: MainFrame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MainFrame.cpp -o $(OBJDIR_RELEASE)/MainFrame.o

$(OBJDIR_RELEASE)/DRC1200App.o: DRC1200App.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DRC1200App.cpp -o $(OBJDIR_RELEASE)/DRC1200App.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

